name: Check links

# Check spelling on the 2nd day of the month.
# 2nd as the first letter of this repo is the 2nd letter in the alphabet.
on:
  push:
    paths:
      - '**.md'
      - .github/workflows/check_links.yaml
      - mlc_config.json
  pull_request:
    paths:
      - '**.md'
      - .github/workflows/check_links.yaml
      - mlc_config.json
  schedule:
  - cron: "0 0 2 * *"

jobs:
  check-links:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: 'mlc_config.json'

