# Check that there is correct markdown in all files
name: Check markdown

# Check spelling on the 2nd day of the month.
# 2nd as the first letter of this repo is the 2nd letter in the alphabet.
on:
  push:
    paths:
      - .github/workflows/check_markdown.yaml
      - "**.md"
      - .markdownlintignore
      - .markdownlint.jsonc
  pull_request:
    paths:
      - .github/workflows/check_markdown.yaml
      - "**.md"
      - .markdownlintignore
      - .markdownlint.jsonc
  schedule:
    - cron: "0 0 2 * *"

jobs:
  check_markdown:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name: Set up Git repository
        uses: actions/checkout@v4

      - uses: articulate/actions-markdownlint@v1
        with:
          config: .markdownlint.jsonc
          ignore: .markdownlintignore


