name: R-CMD-check with BEAST2 installed

# Check spelling on the 2nd day of the month.
# 2nd as the first letter of this repo is the 2nd letter in the alphabet.
on:
  push:
    paths:
      - .github/workflows/R-CMD-check_with_beast2.yaml
      - "**.R"
      - "**.Rmd"
      - DESCRIPTION
      - .Rbuildignore
  pull_request:
    paths:
      - .github/workflows/R-CMD-check_with_beast2.yaml
      - "**.R"
      - "**.Rmd"
      - DESCRIPTION
      - .Rbuildignore
  schedule:
    - cron: "0 0 2 * *"

jobs:
  R-CMD-check_with_beast2:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install libcurl4-openssl-dev
        run: sudo apt install -qq libcurl4-openssl-dev

      - name: Fix rJava error # from https://travis-ci.community/t/cannot-connect-to-java-from-r/9754/8
        run: sudo $(which R) CMD javareconf

      - name: Install fonts # from https://github.com/r-lib/systemfonts/issues/35#issuecomment-961900755
        run: sudo apt install -qq libfontconfig1-dev

      - name: Install libharfbuzz-dev and libfribidi-dev
        run: sudo apt install -qq libharfbuzz-dev libfribidi-dev

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_cran("shiny")
          remotes::install_cran("devtools")
          remotes::install_github("ropensci/beautier", ref = "develop")
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("rcmdcheck")
          remotes::install_cran("covr")
          remotes::install_cran("lintr")
          remotes::install_github("MangoTheCat/goodpractice")
        shell: Rscript {0}

      - name: Install BEAST2
        run: ./scripts/install_beast2.sh

      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}

      - name: Make sure that no files are created in the beautier .cache folder
        run: testthat::expect_equal(0, length(list.files(rappdirs::user_cache_dir(appname = "beautier"))))
        shell: Rscript {0}

      - name: Make sure that no files are created in the tracerer .cache folder
        run: testthat::expect_equal(0, length(list.files(rappdirs::user_cache_dir(appname = "tracerer"))))
        shell: Rscript {0}

      - name: Make sure that no files are created in the beastier .cache folder
        run: testthat::expect_equal(0, length(list.files(rappdirs::user_cache_dir(appname = "beastier"))))
        shell: Rscript {0}

      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ropensci/beautier
 
      - name: Report
        run: beastier::beastier_report()
        shell: Rscript {0}
 
